# Site settings
title: Jekyll-materialize
description: > # this means to ignore newlines until "baseurl:"
   Test material design. Jekyll + materialize.css
   
url: "https://ybarz.github.io"
baseurl: "/mat"
logo: <b>myz<b>
paginate: 3
paginate_path: "/page:num/"
owner:
    email: marcoeybarz@gmail.com
    facebook:
        show: false
        name: "Ichihara Rifa"
        url: "https://fb.me/nasya.aidan"
    github:
        show: false
        username: "riefachan"
    twitter:
        show: false
        username: ""
    disqus:
        show: false
        username: "ichihararifa"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: redcarpet
highlighter: pygments
gems:
    - jekyll-feed
